create table IF NOT EXISTS task (t_id bigint generated by default as identity, description varchar(255) not null, name varchar(255) not null, todolist_tdl_id bigint not null, primary key (t_id));
create table IF NOT EXISTS to_do_list (tdl_id bigint generated by default as identity, name varchar(255) not null, primary key (tdl_id));
